package com.clinic.dao.sqlite;

import com.clinic.dao.DatabaseConnection;
import com.clinic.dao.PatientDao;
import com.clinic.model.Patient;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

// SQLite database implementation for PatientDao interface
// Handles inserting, reading, updating, deleting, and searching patients in SQLite
public class SqlitePatientDao implements PatientDao {

    // Saves a new patient to the database and retrieves the auto-generated ID
    @Override
    public Patient save(Patient patient) {
        String sql = """
            INSERT INTO patients (first_name, last_name, email, phone, date_of_birth, blood_group)
            VALUES (?, ?, ?, ?, ?, ?);
            """;

        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {

            pstmt.setString(1, patient.getFirstName());
            pstmt.setString(2, patient.getLastName());
            pstmt.setString(3, patient.getEmail());
            pstmt.setString(4, patient.getPhone());
            pstmt.setString(5, patient.getDateOfBirth().toString());
            pstmt.setString(6, patient.getBloodGroup());
            pstmt.executeUpdate();

            // Retrieve the auto-increment ID generated by SQLite
            try (ResultSet generatedKeys = pstmt.getGeneratedKeys()) {
                if (generatedKeys.next()) {
                    long generatedId = generatedKeys.getLong(1);
                    return new Patient(
                            generatedId,
                            patient.getFirstName(),
                            patient.getLastName(),
                            patient.getEmail(),
                            patient.getPhone(),
                            patient.getDateOfBirth(),
                            patient.getBloodGroup()
                    );
                } else {
                    throw new SQLException("Patient insertion succeeded, but no generated ID was obtained.");
                }
            }
        } catch (SQLException e) {
            throw new RuntimeException("Failed to insert patient into SQLite database", e);
        }
    }

    // Finds a patient by their primary key ID
    @Override
    public Optional<Patient> findById(Long id) {
        String sql = "SELECT id, first_name, last_name, email, phone, date_of_birth, blood_group FROM patients WHERE id = ?;";

        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setLong(1, id);
            try (ResultSet rs = pstmt.executeQuery()) {
                if (rs.next()) {
                    return Optional.of(mapRowToPatient(rs));
                }
            }
        } catch (SQLException e) {
            throw new RuntimeException("Error querying patient with ID: " + id, e);
        }
        return Optional.empty();
    }

    // Searches patients whose first name or last name contains the search term
    @Override
    public List<Patient> searchByName(String searchTerm) {
        String sql = """
            SELECT id, first_name, last_name, email, phone, date_of_birth, blood_group
            FROM patients
            WHERE first_name LIKE ? OR last_name LIKE ?
            ORDER BY last_name, first_name;
            """;
        List<Patient> patients = new ArrayList<>();
        String wildCard = "%" + (searchTerm == null ? "" : searchTerm.trim()) + "%";

        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setString(1, wildCard);
            pstmt.setString(2, wildCard);
            try (ResultSet rs = pstmt.executeQuery()) {
                while (rs.next()) {
                    patients.add(mapRowToPatient(rs));
                }
            }
        } catch (SQLException e) {
            throw new RuntimeException("Error searching patients with term: " + searchTerm, e);
        }
        return patients;
    }

    // Finds a single patient by their unique email address
    @Override
    public Optional<Patient> findByEmail(String email) {
        String sql = "SELECT id, first_name, last_name, email, phone, date_of_birth, blood_group FROM patients WHERE email = ?;";
        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {
            pstmt.setString(1, email);
            try (ResultSet rs = pstmt.executeQuery()) {
                if (rs.next()) {
                    return Optional.of(mapRowToPatient(rs));
                }
            }
        } catch (SQLException e) {
            throw new RuntimeException("Error finding patient by email: " + email, e);
        }
        return Optional.empty();
    }

    // Retrieves all patients from the database
    @Override
    public List<Patient> findAll() {
        String sql = "SELECT id, first_name, last_name, email, phone, date_of_birth, blood_group FROM patients ORDER BY id;";
        List<Patient> patients = new ArrayList<>();
        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql);
             ResultSet rs = pstmt.executeQuery()) {
            while (rs.next()) {
                patients.add(mapRowToPatient(rs));
            }
        } catch (SQLException e) {
            throw new RuntimeException("Error retrieving all patients", e);
        }
        return patients;
    }

    // Updates an existing patient record in the database
    @Override
    public boolean update(Patient patient) {
        String sql = """
            UPDATE patients
            SET first_name = ?, last_name = ?, email = ?, phone = ?, date_of_birth = ?, blood_group = ?
            WHERE id = ?;
            """;
        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {
            pstmt.setString(1, patient.getFirstName());
            pstmt.setString(2, patient.getLastName());
            pstmt.setString(3, patient.getEmail());
            pstmt.setString(4, patient.getPhone());
            pstmt.setString(5, patient.getDateOfBirth().toString());
            pstmt.setString(6, patient.getBloodGroup());
            pstmt.setLong(7, patient.getId());
            return pstmt.executeUpdate() > 0;
        } catch (SQLException e) {
            throw new RuntimeException("Error updating patient ID: " + patient.getId(), e);
        }
    }

    // Deletes a patient by ID and returns true if a row was removed
    @Override
    public boolean deleteById(Long id) {
        String sql = "DELETE FROM patients WHERE id = ?;";
        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {
            pstmt.setLong(1, id);
            return pstmt.executeUpdate() > 0;
        } catch (SQLException e) {
            throw new RuntimeException("Error deleting patient ID: " + id, e);
        }
    }

    // Helper method to convert a database row into a Patient object
    private Patient mapRowToPatient(ResultSet rs) throws SQLException {
        return new Patient(
                rs.getLong("id"),
                rs.getString("first_name"),
                rs.getString("last_name"),
                rs.getString("email"),
                rs.getString("phone"),
                LocalDate.parse(rs.getString("date_of_birth")),
                rs.getString("blood_group")
        );
    }
}